name: NeuraPulse Cleanup

on:
  push:
    paths:
      - 'run-cleanup.txt'

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Cleanup Script
        run: python neurapulse_cleanup.py

      - name: Commit cleaned files
        run: |
          git config user.email "cleanup@neurapulse.ai"
          git config user.name "NeuraPulse Cleanup Bot"
          git add -A
          git diff --staged --quiet && echo "Already clean!" || git commit -m "[bot] Remove all NeuraPulse injected code [skip ci]"
          git push origin HEAD
